### ISSUE TITLE
 Na aula 2, o ConfigMap apresenta o erro : undefined: ckafka.ConfigMap.

### ISSUE THREAD

**Issue by zeroskullx** [devfullcycle/imersao13#1]
Estou usando o Windows 11 e estou tendo um problema ao importar o kafka. Ao utilizar o seguinte código: 

```go
import (
    ckafka "github.com/confluentinc/confluent-kafka-go/kafka"
)

func main() {
    configMap := &ckafka.ConfigMap{}
    //....
}
```
Ocorre o erro: 'undefined: ckafka.ConfigMap'. Como posso resolver esse problema?

**Comment by rebecanonato89** [comment]
Você tem que rodar o projeto go dentro de um terminar ubuntu - WSL2.
Se está usando o windows 11, instala o Ubuntu para Windows (pode ser pelo Microsoft store)
Se vc já tiver instalado o ubuntu, roda ele pelo seu terminal do vs code, e verifica se vc já tem o Go instalado nele, rodando ```go version```.
 Se já tiver instalado, verifica a versão que vc possui. 1.20.5
 
 você pode seguir o tutorial do proprio Go para linux https://go.dev/doc/install

**Comment by LucianTavares** [comment]
Olá Rogério.

Se puder me chamar no Discord: luciantavares por favor.

Mas os passos para resolver estão abaixo:

Basta ativar a biblioteca do C nas variáveis de ambiente do Golang, executando este comando:
`go env -w CGO_ENABLED=1`

Se der o erro 
`cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`

Basta instalar a biblioteca do C, com os seguintes comandos:
```
sudo apt update
sudo apt install build-essential
```

**Comment by argentinaluiz** [comment]
> Olá Rogério.
> 
> Se puder me chamar no Discord: luciantavares por favor.
> 
> Mas os passos para resolver estão abaixo:
> 
> Basta ativar a biblioteca do C nas variáveis de ambiente do Golang, executando este comando: `go env -w CGO_ENABLED=1`
> 
> Se der o erro `cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`
> 
> Basta instalar a biblioteca do C, com os seguintes comandos:
> 
> ```
> sudo apt update
> sudo apt install build-essential
> ```

Esta é a solução para este problema!

**Comment by matheusfols** [comment]
Estou com o mesmo problema, só que parece ser mais complexo. Já que não consigo nem instalar o Ubuntu pela loja da microsoft.

Dando o seguinte erro: 0x800706d9 e só isso

**Comment by LucianTavares** [comment]
Olá @matheusfols, vamos ter uma live agora as 14:30 no Discord: https://discord.com/channels/917202955952881735/1095434805082079313/1181990669246537779

Nela vamos falar sobre ambiente, se puder entre lá e caso não consiga resolver com as dicas que passarmos, então você me chama no Discord: luciantavares, e vemos juntos isso.

**Comment by matheusfols** [comment]
@LucianTavares não consegui entrar na live, mas testando soluções consegui usando seguindo a instalação manual.
Seguindo esses passos: https://learn.microsoft.com/pt-br/windows/wsl/install-manual

**Comment by LucianTavares** [comment]
Legal, qualquer dúvida nos avise por favor.

Vou deixar abaixo um tutorial para instalação do WSL2, algo que você já fez, mas neste tutorial temos também os passos para instalar e configurar o Docker Engine dentro do WSL2.
https://github.com/codeedu/wsl2-docker-quickstart
