### ISSUE TITLE
"cannot use ckafka.PartitionAny"

### ISSUE THREAD

**Issue by gabrielgpavao** [devfullcycle/imersao13#2]
**Na aula 2, é criado o arquivo `producer.go` para configurar o Producer do Kafka.**

**Problema:**
Dentro do método Publish é declarada uma variável "message" e a ela é atribuído um `&ckafka.Message`
Logo após isso é retornado o seguinte erro:

![Error - PartitionAny invalid type](https://github.com/devfullcycle/imersao13/assets/110189424/d758afa6-ae9a-403a-a4d3-e93d15bb30f4)

O código está idêntico ao do repositório da imersão.
Qual pode ser o problema?

**Contexto:**
Estou usando o WSL2

**Comment by argentinaluiz** [comment]
Olá Gabriel, tudo bem?

Rode este comando no terminal do WSL:
```bash
go mod download github.com/stretchr/objx
```

Me fale se conseguiu evoluir com isto, ok?

**Comment by gabrielgpavao** [comment]
Opa, fala Luiz. Tudo certo?
Obrigadão pelo suporte irmão. Funcionou direitinho!

**Comment by valentimcanejo** [comment]
> ```shell
> go mod download github.com/stretchr/objx
> ```

Boa tarde, eu estou com o mesmo problema, fiz download do pacote citado e também coloquei "go env -w CGO_ENABLED=1", mas não funcionou.
