### ISSUE TITLE
cannot use ckafka.PartitionAny (constant unknown with invalid type) as int32 value in struct literal

### ISSUE THREAD

**Issue by JoaoRafa19** [devfullcycle/imersao13#4]
Na aula 2, é criado o arquivo producer.go para configurar o Producer do Kafka.

Problema:
Dentro do método Publish é declarada uma variável "message" e a ela é atribuído um &ckafka.Message e tem a propriedade Partition que é atribuida um `ckafka.PartitionAny`
Logo após isso é retornado o seguinte erro:
![image](https://github.com/devfullcycle/imersao13/assets/50741246/dabe12f3-44fe-4150-9d47-fd5f2c1a7aae)

**Comment by LucianTavares** [comment]
Olá João.

Tudo bem com você?

Vamos ativar a biblioteca do C nas variáveis de ambiente do Golang, executando este comando:
`go env -w CGO_ENABLED=1`

Se der o erro 
`cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`

Basta instalar a biblioteca do C, com os seguintes comandos:
```
sudo apt update
sudo apt install build-essential
```

Daí, basta executar a aplicação 

Faça o teste e nos diga se deu certo.

**Comment by JoaoRafa19** [comment]
Funcionou Obrigado
